module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("Users", [
      // Recepcionistas (6)
      // Turno mañana 
      {
        dni: 20000001,
        nombre: "Ana",
        apellido: "Lopez",
        contacto: 2772000010,
        email: "ana.lopez25@example.com",
        sexo: "mujer",
        edad: 30,
        rol: "Recepcionista",
        turno: "mañana",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000002,
        nombre: "Carlos",
        apellido: "Ramirez",
        contacto: 2772000040,
        email: "carlos.ramirez40@example.com",
        sexo: "hombre",
        edad: 40,
        rol: "Recepcionista",
        turno: "mañana",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      // Turno tarde 
      {
        dni: 20000003,
        nombre: "Luis",
        apellido: "Martinez",
        contacto: 2772000020,
        email: "luis.martinez30@example.com",
        sexo: "hombre",
        edad: 35,
        rol: "Recepcionista",
        turno: "tarde",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000004,
        nombre: "Lucia",
        apellido: "Fernandez",
        contacto: 2772000050,
        email: "lucia.fernandez32@example.com",
        sexo: "mujer",
        edad: 32,
        rol: "Recepcionista",
        turno: "tarde",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      // Turno noche 
      {
        dni: 20000005,
        nombre: "Pedro",
        apellido: "Lopez",
        contacto: 2772000060,
        email: "pedro.lopez29@example.com",
        sexo: "hombre",
        edad: 29,
        rol: "Recepcionista",
        turno: "noche",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000006,
        nombre: "Sofia",
        apellido: "Diaz",
        contacto: 2772000030,
        email: "sofia.diaz28@example.com",
        sexo: "mujer",
        edad: 28,
        rol: "Recepcionista",
        turno: "noche",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },

      // Enfermeros (18)
      // Turno mañana
      {
        dni: 20000007,
        nombre: "Eva",
        apellido: "Sanchez",
        contacto: 2772000071,
        email: "eva.sanchez27@example.com",
        sexo: "mujer",
        edad: 27,
        rol: "Enfermero",
        turno: "mañana",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000008,
        nombre: "Javier",
        apellido: "Morales",
        contacto: 2772000082,
        email: "javier.morales33@example.com",
        sexo: "hombre",
        edad: 33,
        rol: "Enfermero",
        turno: "mañana",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000009,
        nombre: "Laura",
        apellido: "Vargas",
        contacto: 2772000093,
        email: "laura.vargas30@example.com",
        sexo: "mujer",
        edad: 30,
        rol: "Enfermero",
        turno: "mañana",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },

      // Turno tarde
      {
        dni: 20000010,
        nombre: "Marco",
        apellido: "Paredes",
        contacto: 2772000104,
        email: "marco.paredes26@example.com",
        sexo: "hombre",
        edad: 26,
        rol: "Enfermero",
        turno: "tarde",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000011,
        nombre: "Sara",
        apellido: "Cruz",
        contacto: 2772000115,
        email: "sara.cruz24@example.com",
        sexo: "mujer",
        edad: 24,
        rol: "Enfermero",
        turno: "tarde",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000012,
        nombre: "Andres",
        apellido: "Lopez",
        contacto: 2772000126,
        email: "andres.lopez29@example.com",
        sexo: "hombre",
        edad: 29,
        rol: "Enfermero",
        turno: "tarde",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },

      // Turno noche
      {
        dni: 20000013,
        nombre: "Marta",
        apellido: "Jimenez",
        contacto: 2772000137,
        email: "marta.jimenez31@example.com",
        sexo: "mujer",
        edad: 31,
        rol: "Enfermero",
        turno: "noche",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000014,
        nombre: "Roberto",
        apellido: "Diaz",
        contacto: 2772000148,
        email: "roberto.diaz35@example.com",
        sexo: "hombre",
        edad: 35,
        rol: "Enfermero",
        turno: "noche",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000015,
        nombre: "Clara",
        apellido: "Martinez",
        contacto: 2772000159,
        email: "clara.martinez28@example.com",
        sexo: "mujer",
        edad: 28,
        rol: "Enfermero",
        turno: "noche",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },

      // Médicos (9)
      // Turno mañana
      {
        dni: 20000016,
        nombre: "Dr. Juan",
        apellido: "Lopez",
        contacto: 2772000160,
        email: "juan.lopez45@example.com",
        sexo: "hombre",
        edad: 45,
        rol: "Medico",
        turno: "mañana",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000017,
        nombre: "Dra. Elena",
        apellido: "Juarez",
        contacto: 2772040160,
        email: "elena.juarez@example.com",
        sexo: "mujer",
        edad: 48,
        rol: "Medico",
        turno: "mañana",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000018,
        nombre: "Dra. Laura",
        apellido: "Allende",
        contacto: 2772300160,
        email: "lauri.all@example.com",
        sexo: "mujer",
        edad: 32,
        rol: "Medico",
        turno: "mañana",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      // Turno tarde
      {
        dni: 20000019,
        nombre: "Dra. Lucia",
        apellido: "Martinez",
        contacto: 2772000171,
        email: "lucia.martinez42@example.com",
        sexo: "mujer",
        edad: 42,
        rol: "Medico",
        turno: "tarde",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000020,
        nombre: "Dr. Mario",
        apellido: "Martinez",
        contacto: 2772030171,
        email: "m.martinez52@example.com",
        sexo: "hombre",
        edad: 59,
        rol: "Medico",
        turno: "tarde",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000021,
        nombre: "Dr. Dario",
        apellido: "Avellaneda",
        contacto: 2772034171,
        email: "avellaneda@example.com",
        sexo: "hombre",
        edad: 42,
        rol: "Medico",
        turno: "tarde",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      // Turno noche
      {
        dni: 20000022,
        nombre: "Dr. Carlos",
        apellido: "Gomez",
        contacto: 2772000182,
        email: "carlos.gomez50@example.com",
        sexo: "hombre",
        edad: 50,
        rol: "Medico",
        turno: "noche",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000023,
        nombre: "Dr. Jose",
        apellido: "Pepe",
        contacto: 2772043182,
        email: "pejopese@example.com",
        sexo: "hombre",
        edad: 51,
        rol: "Medico",
        turno: "noche",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
      {
        dni: 20000024,
        nombre: "Dr. Lazaro",
        apellido: "Gane",
        contacto: 2772143182,
        email: "lazaro@example.com",
        sexo: "hombre",
        edad: 28,
        rol: "Medico",
        turno: "noche",
        fecha_creacion: new Date(2025, 6, 1),
        fecha_actualizacion: new Date(2025, 6, 1),
      },
    ], {});
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("Users", null, {});
  },
};