module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Medical_Histories', [
      {
        patient_dni: 35123123,
        enfermedades_previas: "Hipertensión, asma",
        intervenciones_previas: "Apendicectomía",
        alergias: "Penicilina",
        vacunas: "Hepatitis B, Tétanos, COVID-19 (2 dosis)",
        medicamentos_actuales: "Enalapril, Salbutamol",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Baja en carbohidratos",
        insomnio: true,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 36123123,
        enfermedades_previas: "Diabetes tipo 2",
        intervenciones_previas: "Cesárea",
        alergias: "Sulfa",
        vacunas: "Influenza, MMR, COVID-19 (3 dosis)",
        medicamentos_actuales: "Metformina",
        enfermedades_hereditarias: "Diabetes, hipertensión",
        dieta: "Vegana",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: true,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 37123123,
        enfermedades_previas: "Gastritis crónica",
        intervenciones_previas: "Ninguna",
        alergias: "Lactosa",
        vacunas: "Tétanos, Hepatitis A, COVID-19 (2 dosis)",
        medicamentos_actuales: "Omeprazol",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Libre de gluten",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 38123123,
        enfermedades_previas: "Hipotiroidismo",
        intervenciones_previas: "Histerectomía",
        alergias: "Ninguna",
        vacunas: "Hepatitis B, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Levotiroxina",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Hipocalórica",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 2,
        abortos: 1,
        metodos_anticonceptivos: "DIU",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 39123123,
        enfermedades_previas: "Asma, rinitis alérgica",
        intervenciones_previas: "Ninguna",
        alergias: "Polvo",
        vacunas: "Tétanos, MMR, COVID-19 (2 dosis)",
        medicamentos_actuales: "Salbutamol",
        enfermedades_hereditarias: "Asma",
        dieta: "Proteica",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 40123123,
        enfermedades_previas: "Migrañas",
        intervenciones_previas: "Ninguna",
        alergias: "Ibuprofeno",
        vacunas: "Hepatitis B, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Sumatriptán",
        enfermedades_hereditarias: "Migrañas",
        dieta: "Paleo",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 41123123,
        enfermedades_previas: "Epilepsia",
        intervenciones_previas: "Cesárea",
        alergias: "Aspirina",
        vacunas: "Polio, MMR, COVID-19 (2 dosis)",
        medicamentos_actuales: "Levetiracetam",
        enfermedades_hereditarias: "Epilepsia",
        dieta: "Vegetariana",
        insomnio: true,
        sustancias: "Ninguna",
        embarazo: true,
        hijos: 3,
        abortos: 0,
        metodos_anticonceptivos: "Implante",
        convulciones: true,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 42123123,
        enfermedades_previas: "No tiene enfermedades previas",
        intervenciones_previas: "Apendicectomía",
        alergias: "Ninguna",
        vacunas: "Tétanos, MMR, COVID-19 (3 dosis)",
        medicamentos_actuales: "Ninguno",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Hipercalórica",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 43123123,
        enfermedades_previas: "Hipertensión, diabetes tipo 1",
        intervenciones_previas: "Apendicectomía, colecistectomía",
        alergias: "Sulfa",
        vacunas: "Hepatitis B, Tétanos, COVID-19 (2 dosis)",
        medicamentos_actuales: "Insulina, Enalapril",
        enfermedades_hereditarias: "Diabetes",
        dieta: "Baja en grasa",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 44123123,
        enfermedades_previas: "Tensión alta",
        intervenciones_previas: "Apendicectomía",
        alergias: "Pescado",
        vacunas: "Polio, Hepatitis A, COVID-19 (2 dosis)",
        medicamentos_actuales: "Amlodipina",
        enfermedades_hereditarias: "Hipertensión",
        dieta: "Baja en carbohidratos",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 45123123,
        enfermedades_previas: "Artritis reumatoide",
        intervenciones_previas: "Cirugía de rodilla",
        alergias: "Ibuprofeno",
        vacunas: "Tétanos, MMR, COVID-19 (3 dosis)",
        medicamentos_actuales: "Metotrexato",
        enfermedades_hereditarias: "Artritis",
        dieta: "Vegetariana",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 46123123,
        enfermedades_previas: "Dislipidemia",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Hepatitis B, COVID-19 (2 dosis)",
        medicamentos_actuales: "Atorvastatina",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Hipercalórica",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752245,
        enfermedades_previas: "Enfermedad renal crónica",
        intervenciones_previas: "Diálisis peritoneal",
        alergias: "Penicilina",
        vacunas: "Tétanos, Hepatitis A, COVID-19 (3 dosis)",
        medicamentos_actuales: "Lisinopril, Epoetina",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Baja en sodio",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 2,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10123123,
        enfermedades_previas: "Migrañas, ansiedad",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Polio, Tétanos, COVID-19 (2 dosis)",
        medicamentos_actuales: "Alprazolam, Sumatriptán",
        enfermedades_hereditarias: "Migrañas",
        dieta: "Baja en grasa",
        insomnio: true,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 12123123,
        enfermedades_previas: "Endometriosis",
        intervenciones_previas: "Histerectomía parcial",
        alergias: "Ibuprofeno",
        vacunas: "Hepatitis B, MMR, COVID-19 (2 dosis)",
        medicamentos_actuales: "Naproxeno",
        enfermedades_hereditarias: "Endometriosis",
        dieta: "Proteica",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: true,
        hijos: 2,
        abortos: 0,
        metodos_anticonceptivos: "DIU",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 13123123,
        enfermedades_previas: "Alergias estacionales, hipertensión",
        intervenciones_previas: "Cirugía de hernia",
        alergias: "Ácaros",
        vacunas: "Tétanos, Polio, COVID-19 (3 dosis)",
        medicamentos_actuales: "Losartán",
        enfermedades_hereditarias: "Hipertensión",
        dieta: "Hipocalórica",
        insomnio: false,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 14123123,
        enfermedades_previas: "Sinusitis crónica",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Hepatitis A, MMR, COVID-19 (2 dosis)",
        medicamentos_actuales: "Descongestionante nasal",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Libre de gluten",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 15123123,
        enfermedades_previas: "Gastritis, colitis",
        intervenciones_previas: "Apendicectomía",
        alergias: "Gluten",
        vacunas: "Polio, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Omeprazol",
        enfermedades_hereditarias: "Colitis",
        dieta: "Libre de gluten",
        insomnio: true,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 16123123,
        enfermedades_previas: "No tiene enfermedades previas",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Hepatitis B, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Ninguno",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Proteica",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 17123123,
        enfermedades_previas: "Depresión, ansiedad",
        intervenciones_previas: "Ninguna",
        alergias: "Pescado",
        vacunas: "Polio, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Sertralina",
        enfermedades_hereditarias: "Depresión",
        dieta: "Hipercalórica",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 18123123,
        enfermedades_previas: "Sinusitis, asma",
        intervenciones_previas: "Ninguna",
        alergias: "Polvo",
        vacunas: "Tétanos, Hepatitis B, COVID-19 (2 dosis)",
        medicamentos_actuales: "Salbutamol",
        enfermedades_hereditarias: "Asma",
        dieta: "Baja en carbohidratos",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: true,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 19123123,
        enfermedades_previas: "Epilepsia, hipertensión",
        intervenciones_previas: "Apendicectomía",
        alergias: "Ninguna",
        vacunas: "Polio, Hepatitis A, COVID-19 (3 dosis)",
        medicamentos_actuales: "Carbamazepina, Losartán",
        enfermedades_hereditarias: "Epilepsia",
        dieta: "Proteica",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: true,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 20123123,
        enfermedades_previas: "No tiene enfermedades previas",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Hepatitis B, Tétanos, COVID-19 (2 dosis)",
        medicamentos_actuales: "Ninguno",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Baja en carbohidratos",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 2,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 21123123,
        enfermedades_previas: "Hipotiroidismo",
        intervenciones_previas: "Cirugía de tiroides",
        alergias: "Yodo",
        vacunas: "Tétanos, Hepatitis A, COVID-19 (3 dosis)",
        medicamentos_actuales: "Levotiroxina",
        enfermedades_hereditarias: "Hipotiroidismo",
        dieta: "Vegetariana",
        insomnio: true,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 22123123,
        enfermedades_previas: "Gastritis, reflujo",
        intervenciones_previas: "Ninguna",
        alergias: "Lactosa",
        vacunas: "Polio, Hepatitis B, COVID-19 (2 dosis)",
        medicamentos_actuales: "Omeprazol",
        enfermedades_hereditarias: "Gastritis",
        dieta: "Libre de gluten",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 23123123,
        enfermedades_previas: "Hernia discal, hipertensión",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Tétanos, MMR, COVID-19 (3 dosis)",
        medicamentos_actuales: "Amlodipina",
        enfermedades_hereditarias: "Hipertensión",
        dieta: "Baja en grasa",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 24123123,
        enfermedades_previas: "Sinusitis crónica, hipertensión",
        intervenciones_previas: "Apendicectomía",
        alergias: "Aspirina",
        vacunas: "Hepatitis B, COVID-19 (2 dosis)",
        medicamentos_actuales: "Losartán, Furosemida",
        enfermedades_hereditarias: "Hipertensión",
        dieta: "Proteica",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 2,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 25123123,
        enfermedades_previas: "Asma, alergias estacionales",
        intervenciones_previas: "Ninguna",
        alergias: "Polvo",
        vacunas: "Tétanos, Polio, COVID-19 (2 dosis)",
        medicamentos_actuales: "Salbutamol",
        enfermedades_hereditarias: "Asma",
        dieta: "Libre de gluten",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 26123123,
        enfermedades_previas: "Depresión, diabetes tipo 2",
        intervenciones_previas: "Cesárea",
        alergias: "Ninguna",
        vacunas: "MMR, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Metformina, Sertralina",
        enfermedades_hereditarias: "Diabetes",
        dieta: "Hipocalórica",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: true,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "DIU",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 27123123,
        enfermedades_previas: "No tiene enfermedades previas",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Hepatitis B, COVID-19 (2 dosis)",
        medicamentos_actuales: "Ninguno",
        enfermedades_hereditarias: "Ninguna",
        dieta: "Baja en grasa",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752234,
        enfermedades_previas: "Epilepsia, colesterol alto",
        intervenciones_previas: "Apendicectomía",
        alergias: "Penicilina",
        vacunas: "Polio, Hepatitis A, COVID-19 (3 dosis)",
        medicamentos_actuales: "Ácido valproico, Atorvastatina",
        enfermedades_hereditarias: "Epilepsia",
        dieta: "Baja en carbohidratos",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: true,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752235,
        enfermedades_previas: "Asma, artritis reumatoide",
        intervenciones_previas: "Cirugía de rodilla",
        alergias: "Aspirina",
        vacunas: "Hepatitis B, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Salbutamol, Metotrexato",
        enfermedades_hereditarias: "Artritis reumatoide",
        dieta: "Vegetariana",
        insomnio: false,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 2,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752236,
        enfermedades_previas: "Hipotiroidismo, hipertensión",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Tétanos, Hepatitis B, COVID-19 (2 dosis)",
        medicamentos_actuales: "Levotiroxina, Losartán",
        enfermedades_hereditarias: "Hipotiroidismo",
        dieta: "Hipocalórica",
        insomnio: true,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752237,
        enfermedades_previas: "Sinusitis, diabetes tipo 2",
        intervenciones_previas: "Cirugía de vesícula biliar",
        alergias: "Ninguna",
        vacunas: "Hepatitis A, Polio, COVID-19 (3 dosis)",
        medicamentos_actuales: "Metformina, Fluticasona",
        enfermedades_hereditarias: "Diabetes",
        dieta: "Proteica",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752238,
        enfermedades_previas: "Hipertensión, apnea del sueño",
        intervenciones_previas: "Cirugía de corazón",
        alergias: "Aspirina",
        vacunas: "Hepatitis B, COVID-19 (3 dosis)",
        medicamentos_actuales: "Losartán, CPAP",
        enfermedades_hereditarias: "Hipertensión",
        dieta: "Baja en grasa",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752239,
        enfermedades_previas: "Sinusitis, migrañas",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Polio, Hepatitis A, COVID-19 (2 dosis)",
        medicamentos_actuales: "Sumatriptán",
        enfermedades_hereditarias: "Migrañas",
        dieta: "Baja en carbohidratos",
        insomnio: true,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752240,
        enfermedades_previas: "Diabetes tipo 1, colesterol alto",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Hepatitis B, COVID-19 (3 dosis)",
        medicamentos_actuales: "Insulina, Atorvastatina",
        enfermedades_hereditarias: "Diabetes",
        dieta: "Baja en carbohidratos",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752241,
        enfermedades_previas: "Artritis reumatoide, depresión",
        intervenciones_previas: "Cirugía de hombro",
        alergias: "Aspirina",
        vacunas: "Hepatitis A, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Metotrexato, Sertralina",
        enfermedades_hereditarias: "Artritis",
        dieta: "Vegetariana",
        insomnio: true,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 2,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752242,
        enfermedades_previas: "Sinusitis, hipertensión",
        intervenciones_previas: "Apendicectomía",
        alergias: "Polvo",
        vacunas: "Tétanos, Polio, COVID-19 (2 dosis)",
        medicamentos_actuales: "Losartán",
        enfermedades_hereditarias: "Hipertensión",
        dieta: "Baja en carbohidratos",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752243,
        enfermedades_previas: "Epilepsia, hipotiroidismo",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Hepatitis B, Polio, COVID-19 (3 dosis)",
        medicamentos_actuales: "Carbamazepina, Levotiroxina",
        enfermedades_hereditarias: "Epilepsia, Hipotiroidismo",
        dieta: "Baja en carbohidratos",
        insomnio: true,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: true,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 10752244,
        enfermedades_previas: "Colesterol alto, depresión",
        intervenciones_previas: "Ninguna",
        alergias: "Lactosa",
        vacunas: "Tétanos, Hepatitis B, COVID-19 (3 dosis)",
        medicamentos_actuales: "Simvastatina, Sertralina",
        enfermedades_hereditarias: "Depresión, colesterol alto",
        dieta: "Hipocalórica",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 2,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 28123123, // Mujer
        enfermedades_previas: "Asma, migrañas",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Polio, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Salbutamol, Sumatriptán",
        enfermedades_hereditarias: "Migrañas",
        dieta: "Vegetariana",
        insomnio: true,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 2,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 29123123, // Hombre
        enfermedades_previas: "Colesterol alto, diabetes tipo 2",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Polio, Hepatitis B, COVID-19 (3 dosis)",
        medicamentos_actuales: "Metformina, Atorvastatina",
        enfermedades_hereditarias: "Diabetes",
        dieta: "Baja en carbohidratos",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 30123123, // Mujer
        enfermedades_previas: "Hipotiroidismo",
        intervenciones_previas: "Ninguna",
        alergias: "Aspirina",
        vacunas: "Hepatitis A, Polio, COVID-19 (2 dosis)",
        medicamentos_actuales: "Levotiroxina",
        enfermedades_hereditarias: "Hipotiroidismo",
        dieta: "Baja en carbohidratos",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 31123123, // Hombre
        enfermedades_previas: "Colesterol alto, diabetes tipo 2",
        intervenciones_previas: "Ninguna",
        alergias: "Ninguna",
        vacunas: "Polio, Hepatitis B, COVID-19 (3 dosis)",
        medicamentos_actuales: "Metformina, Atorvastatina",
        enfermedades_hereditarias: "Diabetes",
        dieta: "Baja en carbohidratos",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 32123123, // Mujer
        enfermedades_previas: "Artritis reumatoide, hipotiroidismo",
        intervenciones_previas: "Ninguna",
        alergias: "Aspirina",
        vacunas: "Hepatitis A, Polio, COVID-19 (3 dosis)",
        medicamentos_actuales: "Metotrexato, Levotiroxina",
        enfermedades_hereditarias: "Artritis reumatoide",
        dieta: "Vegetariana",
        insomnio: false,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 2,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 33123123, // Hombre
        enfermedades_previas: "Enfermedades respiratorias, hipertensión",
        intervenciones_previas: "Cirugía de rodilla",
        alergias: "Polvo",
        vacunas: "Hepatitis B, COVID-19 (3 dosis)",
        medicamentos_actuales: "Losartán, Salbutamol",
        enfermedades_hereditarias: "Hipertensión",
        dieta: "Baja en carbohidratos",
        insomnio: false,
        sustancias: "Ninguna",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Condón",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 34123123, // Mujer
        enfermedades_previas: "Epilepsia, migrañas",
        intervenciones_previas: "Apendicectomía",
        alergias: "Ninguna",
        vacunas: "Tétanos, Polio, COVID-19 (3 dosis)",
        medicamentos_actuales: "Ácido valproico, Sumatriptán",
        enfermedades_hereditarias: "Epilepsia",
        dieta: "Baja en carbohidratos",
        insomnio: true,
        sustancias: "Alcohol",
        embarazo: false,
        hijos: 0,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: true,
        enfermedades_respiratorias: false,
        enfermedades_cardiovasculares: false,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 47123123, // Mujer
        enfermedades_previas: "Sinusitis, colesterol alto",
        intervenciones_previas: "Cirugía de vesícula",
        alergias: "Lactosa",
        vacunas: "Polio, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Simvastatina, Fluticasona",
        enfermedades_hereditarias: "Colesterol alto",
        dieta: "Hipocalórica",
        insomnio: true,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Píldora",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      },
      {
        patient_dni: 48123123, // Hombre
        enfermedades_previas: "Hipertensión, apnea del sueño",
        intervenciones_previas: "Cirugía de corazón",
        alergias: "Aspirina",
        vacunas: "Hepatitis A, Tétanos, COVID-19 (3 dosis)",
        medicamentos_actuales: "Losartán, CPAP",
        enfermedades_hereditarias: "Hipertensión",
        dieta: "Baja en grasa",
        insomnio: false,
        sustancias: "Tabaco",
        embarazo: false,
        hijos: 1,
        abortos: 0,
        metodos_anticonceptivos: "Ninguno",
        convulciones: false,
        enfermedades_respiratorias: true,
        enfermedades_cardiovasculares: true,
        fecha_creacion: new Date(),
        fecha_actualizacion: new Date(),
      }
    ], {});
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Medical_Histories', null, {});
  }
};