module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Beds', [
      // -------------------------------- Salas de consulta 100 ---
      // ALA SUR
      {
        room_number: 101,
        tipo_habitacion: 'consulta general',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 102,
        tipo_habitacion: 'consulta general',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 103,
        tipo_habitacion: 'consulta general',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 104,
        tipo_habitacion: 'consulta general',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 105,
        tipo_habitacion: 'consulta especializada',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 106,
        tipo_habitacion: 'consulta especializada',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ------------------------- Salas de hospitalización 200 ---
      // ALA OESTE (Capacidad: 1)
      {
        room_number: 201,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 202,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 203,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 204,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 205,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 206,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 207,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 208,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 209,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 210,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ALA ESTE (Capacidad: 2)
      {
        room_number: 211,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 212,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 213,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 214,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 215,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 216,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 217,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 218,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 219,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 220,
        tipo_habitacion: 'habitacion de hospitalización',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // -------------------------------- Sala de urgencias 300 ---
      // ALA NORTE
      {
        room_number: 301,
        tipo_habitacion: 'urgencias',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 302,
        tipo_habitacion: 'urgencias',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 303,
        tipo_habitacion: 'urgencias',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 304,
        tipo_habitacion: 'urgencias',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ------------------------------ Cuidados intensivos 400 ---
      // ALA NORTE
      {
        room_number: 401,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 402,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 403,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 404,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 405,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 406,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 407,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 408,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 409,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 410,
        tipo_habitacion: 'cuidados intensivos',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ---------------------------------------- Pediatría 500 ---
      // ALA ESTE
      {
        room_number: 501,
        tipo_habitacion: 'pediatria',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 502,
        tipo_habitacion: 'pediatria',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 503,
        tipo_habitacion: 'pediatria',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 504,
        tipo_habitacion: 'pediatria',
        ala: 'este',
        capacidad: 2,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ----------------------------------- Rehabilitación 600 ---
      // ALA OESTE
      {
        room_number: 601,
        tipo_habitacion: 'rehabilitación',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 602,
        tipo_habitacion: 'rehabilitación',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ------------------------------------- Salud mental 700 ---
      // ALA SUR
      {
        room_number: 701,
        tipo_habitacion: 'salud mental',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 702,
        tipo_habitacion: 'salud mental',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // -------------------------------------- Operaciones 800 ---
      // ALA NORTE
      {
        room_number: 801,
        tipo_habitacion: 'quirofano',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 802,
        tipo_habitacion: 'quirofano',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 803,
        tipo_habitacion: 'quirofano',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 804,
        tipo_habitacion: 'quirofano',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ---------------------- Procedimientos ambulatorios 900 ---
      // ALA OESTE
      {
        room_number: 901,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 902,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 903,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 904,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 905,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 906,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 907,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 908,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 909,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 910,
        tipo_habitacion: 'procedimientos ambulatorios',
        ala: 'oeste',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // -------------------------------------- Radiología 1000 ---
      // ALA SUR
      {
        room_number: 1001,
        tipo_habitacion: 'radiología',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 1002,
        tipo_habitacion: 'radiología',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ------------------------------------- Laboratorio 1100 ---
      // ALA SUR
      {
        room_number: 1101,
        tipo_habitacion: 'laboratorio',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 1102,
        tipo_habitacion: 'laboratorio',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 1103,
        tipo_habitacion: 'laboratorio',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ---------------------------------------- Farmacia 1200 ---
      // ALA NORTE Y SUR
      {
        room_number: 1201,
        tipo_habitacion: 'farmacia',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 1210,
        tipo_habitacion: 'farmacia',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // ------------------------------------- Reanimación 1300 ---
      // ALA NORTE
      {
        room_number: 1301,
        tipo_habitacion: 'reanimación',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 1302,
        tipo_habitacion: 'reanimación',
        ala: 'norte',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      // -------------------------------------- Endoscopia 1400 ---
      // ALA SUR
      {
        room_number: 1401,
        tipo_habitacion: 'endoscopia',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 1402,
        tipo_habitacion: 'endoscopia',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 1403,
        tipo_habitacion: 'endoscopia',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
      {
        room_number: 1404,
        tipo_habitacion: 'endoscopia',
        ala: 'sur',
        capacidad: 1,
        estado: 'limpia',
        restriccion_genero: 'none',
        disponible: true,
      },
    ], {});
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Beds', null, {});
  }
};